### ISSUE TITLE
Errors when running with node 8.11

### ISSUE THREAD

**Issue by mfour-merickson** [klauscfhq/signale#3]
/Users/merickson/Documents/code/node/test-signale/node_modules/signale/signale.js:149
      signale.push(chalk[type.color](type.badge.padEnd(2)));
                                                ^

TypeError: type.badge.padEnd is not a function
    at Signale._buildSignale (/Users/merickson/Documents/code/node/test-signale/node_modules/signale/signale.js:149:49)
    at Signale._logger (/Users/merickson/Documents/code/node/test-signale/node_modules/signale/signale.js:79:20)
    at Object.<anonymous> (/Users/merickson/Documents/code/node/test-signale/index.js:3:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)

**To Reproduce**
Using node 8.11, I have a simple `index.js` calling the same routes that you do in the demo

**Expected behavior**
Expect to see output as shown in demo

**Screenshots**
![image](https://user-images.githubusercontent.com/31225533/40192252-aeb6adc8-59b8-11e8-82f4-95ad45179924.png)

**Technical Info (please complete the following information)**
 - OS: macOS 10.12.6

 - Signale Version: 1.0.1

 - Node.js Version: 8.11 

**Additional context**
I have tested with node 8.9 and newer node versions and all seems to work just fine (seems to be node 8.11 issue -- which is important for us as it is the latest 8.x LTS)

**Comment by mfour-merickson** [comment]
Well, I am not quite sure what happened, but after posting this error (you can see it is indeed an error based on the screenshot) all seems to be working now?   Not quite sure what changed.
