### ISSUE TITLE
TypeError: type.badge.padEnd is not a function in node 6

### ISSUE THREAD

**Issue by Shriram-Balaji** [klauscfhq/signale#46]
**Describe the bug**
Calling signale methods in node 6.11.1 seem to return a TypeError

**To Reproduce**
Call any of the signale methods, in `node 6` environment , it will fail with the following error.

```
  TypeError: type.badge.padEnd is not a function
  Signale._buildSignale (node_modules/signale/signale.js:198:49)
  Signale._logger (node_modules/signale/signale.js:257:20)
  fetch.then.then.catch.e (src/api/subscriptions.api.js:35:15)
```

**Expected behavior**
The logger should work as expected

**Technical Info (please complete the following information)**
 - OS: macOS 10.13.5
 - Signale Version: 1.2.1	
 - Node.js Version: 6.11.2

**Comment by haochuan** [comment]
Same here:

**Describe the bug**
Calling signale methods in node 6.11.4 seem to return a TypeError

**To Reproduce**
Call any of the signale methods, in node 6 environment , it will fail with the following error.

```
TypeError: type.badge.padEnd is not a function
    at Signale._buildSignale (/Users/haochuan/Projects/log-piper/node_modules/signale/signale.js:198:49)
    at Signale._logger (/Users/haochuan/Projects/log-piper/node_modules/signale/signale.js:257:20)
```
**Expected behavior**
The logger should work as expected

**Technical Info (please complete the following information)**

OS: macOS 10.13.4
Signale Version: 1.2.1
Node.js Version: 6.11.4

**Comment by rjoydip** [comment]
@Shriram-Balaji and @haochuan Can you produce some code for this?

**Comment by haochuan** [comment]
@rjoydip 

This is all I have to get the error:

```
const signale = require('signale');
signale.success('Operation successful');
```

**Comment by rjoydip** [comment]
@haochuan I don't understand why this is happening on your end. But it's working fine in here. 😕

**Comment by ThunbergOlle** [comment]
I have got the solution:

This is clientsided. You will have to update your version of Nodejs to the latest.

**Comment by Shriram-Balaji** [comment]
@ThunbergOlle Could you please brief us if you know why exactlyy this is occurring. I do understand that this problem is not occuring in node 8 and above, the problem is that I can't use signale if I want to support node 6 because of the error.

**Comment by ThunbergOlle** [comment]
I don't know why exactly it's occurring. I just wanted to share how other people can fix it that can update the node version. 

There are probally more modules that's similar to this.
